import { Router } from "express";
import { CreateUserController } from "./useCases/CreateUser/CreateUserController";
import { AuthenticateUserController } from "./useCases/authenticateUser/AuthenticateUserController";
import { GetAllUsersController } from "./useCases/getAllUsers/getAllUsersController";
import { ensureAuthenticated } from "./middlewares/ensureAuthenticated";
import { GetOneUserController } from "./useCases/getOneUser/getOneUserController";
import { GetMessagesController } from "./useCases/getMessages/getMessagesController";
import { SendMessageController } from "./useCases/sendMessage/sendMessageController";
import { CreateCheckoutController } from "./useCases/createCheckout/createCheckoutController";
import { StoreTransactionController } from "./useCases/storeTransation/storeTransationController";
import { CreateRoomController } from "./useCases/createRoom/createRoomController";
import { GetRoomByClientAndConsultorController } from "./useCases/getRoomByClientAndConsultor/getRoomByClientAndConsultorController";
import { GetRoomsByUserController } from "./useCases/getRoomsByUser/getRoomsByUserController";
import { UpdateRoomExpiryController } from "./useCases/updateRoom/updateRoomController";
import { UpdateUserController } from './useCases/updateUser/updateUserController';
const router = Router();
const createUserController = new CreateUserController();
const authenticateUserController = new AuthenticateUserController();
const getAllUserController = new GetAllUsersController();
const getOneUserController = new GetOneUserController();
const getMessagesController = new GetMessagesController();
const sendMessageController = new SendMessageController();
const createCheckoutController = new CreateCheckoutController();
const storeTransactionController = new StoreTransactionController();
const createRoomController = new CreateRoomController();
const updateRoomExpiryController = new UpdateRoomExpiryController();
const getRoomByClientAndConsultorController =
  new GetRoomByClientAndConsultorController();
const getRoomsByUserController = new GetRoomsByUserController();
const updateUserController = new UpdateUserController();

router.post("/user", createUserController.handle);
router.post("/login", authenticateUserController.handle);
router.get("/getUsers", getAllUserController.handle);
router.get("/getuser/:id", getOneUserController.handle);
router.get("/getmessages", getMessagesController.handle);
router.post("/sendmessage", sendMessageController.handle);
router.post("/create-checkout", createCheckoutController.handle);
router.post("/store-transactions", storeTransactionController.handle);
router.post("/create-room", createRoomController.handle);
router.get("/get-room", getRoomByClientAndConsultorController.handle);
router.get("/get-rooms/:userId", getRoomsByUserController.handle);
router.post("/update-room-expiry", updateRoomExpiryController.handle);
router.put('/user/:id', updateUserController.handle, ensureAuthenticated);
export { router };
